version: "3.8"

services:
  database:
    image: docker.io/bitnami/postgresql:15
    restart: always
    volumes:
      - './volumes/postgresql/:/bitnami/postgresql'
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
      - POSTGRES_DB=local
      - TZ=Asia/Ho_Chi_Minh
      - POSTGRESQL_TIMEZONE=Asia/Ho_Chi_Minh
    ports:
      - '5432:5432'
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  # # backend:
  #   image: boilerplate/backend
  #   platform: linux/amd64
  #   restart: unless-stopped
  #   build: 
  #     context: .
  #     dockerfile: ./backend/Dockerfile
  #   env_file:
  #     - ./backend/.env
  #   environment:
  #     - DATABASE_NAME=test-prod
  #     - DATABASE_HOST=database
  #     - DATABASE_PORT=3306
  #   depends_on:
  #     - database
  #   ports:
  #     - 5000:5000

  # frontend:
  #   image: boilerplate/frontend
  #   build:
  #     context: .
  #     dockerfile: ./frontend/Dockerfile
  #   ports:
  #     - "3000:80"